- name: "Example Endpoint 1"
  endpoint: "/example1"
  method: "GET"
  data:
    format: "xml"
    payload: |
      <example>
        <id>12345</id>
        <description>Data for the first example</description>
      </example>
  status: 200
  headers:
    Custom-Header: "Value1"

- name: "Example Endpoint 2"
  endpoint: "/example2"
  method: "POST"
  data:
    format: "json"
    payload:
      id: 12345
      description: "Data for the second example"
      foo:
        bar: "baz"
      tags:
        - "example"
        - "test"
  status: 201

- name: "Example Endpoint 3"
  endpoint: "/example3"
  method: "GET"
  data:
    format: "html"
    payload: |
      <html>
        <head>
          <title>Example 3</title>
        </head>
        <body>
          <h1>Example 3</h1>
          <p>This is the third example</p>
        </body>
      </html>
  status: 200

- name: "Not Found Example"
  endpoint: "/notfound"
  status: 404